from django.urls import path
from adminapp import views
urlpatterns=[path('index/',views.index,name='index.html'),
             path('add_category/',views.add_category,name='add_category'),
             path('save_category/',views.save_category,name='save_category'),
             path('display_category/',views.display_category,name='display_category'),
             path('edit_category/<int:cid>',views.edit_category,name='edit_category'),
             path('update_category/<int:cid>',views.update_category,name='update_category'),
             path('delete_category/<int:cid>',views.delete_category,name='delete_category'),
             path('add_product/',views.add_product,name='add_product'),
             path('save_product/',views.save_product,name='save_product'),
             path('display_product/',views.display_product,name='display_product'),
             path('edit_product/<int:pid>',views.edit_product,name='edit_product'),
             path('update_product/<int:pid>',views.update_product,name='update_product'),
             path('delete_product/<int:pid>',views.delete_product,name='delete_product'),
             path('login_page/',views.login_page,name='login_page'),
             path('admin_login/',views.admin_login,name='admin_login'),
             path('singlepage/<int:pid>',views.singlepage,name='singlepage'),
             path('view_messages/',views.view_messages,name='view_messages'),
             path('delete_message/<int:mid>',views.delete_message,name='delete_message')]