# Generated by Django 5.2.7 on 2025-11-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_productdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productdb',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
