# Generated by Django 5.2.7 on 2025-12-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_messagedb'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('totalprice', models.IntegerField(blank=True, null=True)),
                ('productname', models.CharField(blank=True, max_length=30, null=True)),
                ('productprice', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('productimage', models.ImageField(blank=True, null=True, upload_to='product_images')),
            ],
        ),
    ]
